name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: npx semantic-release

      - name: Notify on success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;
            const body = '🎉 Release successful!';
            await github.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;
            const body = '❌ Release failed.';
            await github.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });
